site_name: De Iure
site_description: Конспект для підготовки до вступу і ведення дисциплін під час навчання в Національній академії Служби безпеки України — спеціальність D8 «Право» (заочна форма).
site_author: Samuel E. Morgan
site_url: https://law.morgan-dev.com/
copyright: >
  Public Key (OpenPGP/GPG) for encrypted communication&#58;<br/>
  GPG Key Fingerprint&#58; A7F6 AB83 9DCE 9C2A 64B7 14AB EAFE C4BB F49C C2FA<br/>
  Copyright &copy; 2026 Samuel E. Morgan

theme:
  name: material
  language: uk
  logo: assets/logo.png
  favicon: assets/favicon.svg
  font:
    text: Fira Code
    code: Fira Mono
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
  palette:
    scheme: slate
    primary: black
    accent: red

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/samuel-edmund-morgan
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/samuel-morgan-dev-com
      name: LinkedIn
    - icon: fontawesome/solid/envelope
      link: mailto:samuel@morgan-dev.com
      name: Email
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/semorgana
      name: Docker Hub
    - icon: fontawesome/solid/lock
      link: https://keys.openpgp.org/search?q=A7F6AB839DCE9C2A64B714ABEAFEC4BBF49CC2FA
      name: OpenPGP
    - icon: fontawesome/brands/signal-messenger
      link: https://signal.me/#eu/AbEPOx59v4ASPDxcFZ_7TgAxMniKM3YZhwnKc_tFuunduZ0wG4hLLbcun4spf-Eh
      name: Signal

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/mathjax.js

plugins:
  - search:
      lang:
        - uk
        - en
  - tags

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      permalink_title: Постійне посилання на цей розділ
      toc_depth: 4
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: false
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.tilde

nav:
  - Головна: index.md

  - Підготовка до вступу:
      - підготовка-до-вступу/index.md
      - Дорожня карта вступу: підготовка-до-вступу/дорожня-карта.md
      - Календар підготовки: підготовка-до-вступу/timeline.md

      - Історія України:
          - підготовка-до-вступу/історія/index.md
          - Хронологічна карта: підготовка-до-вступу/історія/хронологічна-карта.md
          - Ключові дати: підготовка-до-вступу/історія/ключові-дати.md
          - Блоки програми:
              - 01. Вступ до історії України: підготовка-до-вступу/історія/блоки/01-вступ.md
              - 02. Стародавня історія: підготовка-до-вступу/історія/блоки/02-стародавня-історія.md
              - 03. Русь-Україна (Київська держава): підготовка-до-вступу/історія/блоки/03-київська-русь.md
              - 04. Галицько-Волинська держава: підготовка-до-вступу/історія/блоки/04-галицько-волинська.md
              - 05. Литовсько-польський період: підготовка-до-вступу/історія/блоки/05-литовсько-польський-період.md
              - 06. Річ Посполита (друга половина XVI ст.): підготовка-до-вступу/історія/блоки/06-річ-посполита-xvi.md
              - 07. Річ Посполита (перша половина XVII ст.): підготовка-до-вступу/історія/блоки/07-річ-посполита-xvii.md
              - 08. Хмельниччина: підготовка-до-вступу/історія/блоки/08-хмельниччина.md
              - 09. Гетьманщина та Руїна: підготовка-до-вступу/історія/блоки/09-гетьманщина-руїна.md
              - 10. Мазепа і Північна війна: підготовка-до-вступу/історія/блоки/10-мазепа.md
              - 11. Ліквідація автономії Гетьманщини: підготовка-до-вступу/історія/блоки/11-ліквідація-автономії.md
              - 12. Російська імперія (початок XIX ст.): підготовка-до-вступу/історія/блоки/12-російська-імперія-початок-xix.md
              - 13. Австрійська імперія (початок XIX ст.): підготовка-до-вступу/історія/блоки/13-австрійська-імперія-початок-xix.md
              - 14. Культура кінця XVIII – першої половини XIX ст.: підготовка-до-вступу/історія/блоки/14-культура-кінця-xviii-першої-половини-xix.md
              - 15. Наддніпрянщина (друга половина XIX ст.): підготовка-до-вступу/історія/блоки/15-наддніпрянщина-друга-половина-xix.md
              - 16. Західна Україна (друга половина XIX ст.): підготовка-до-вступу/історія/блоки/16-західна-україна-друга-половина-xix.md
              - 17. Культура другої половини XIX – початку XX ст.: підготовка-до-вступу/історія/блоки/17-культура-другої-половини-xix.md
              - 18. Наддніпрянщина (1900–1914): підготовка-до-вступу/історія/блоки/18-наддніпрянщина-1900-1914.md
              - 19. Західна Україна (1900–1914): підготовка-до-вступу/історія/блоки/19-західна-україна-1900-1914.md
              - 20. Перша світова війна: підготовка-до-вступу/історія/блоки/20-перша-світова.md
              - 21. Початок Української революції: підготовка-до-вступу/історія/блоки/21-українська-революція-початок.md
              - 22. Боротьба за відновлення державності: підготовка-до-вступу/історія/блоки/22-боротьба-за-державність.md
              - 23. Комуністичний тоталітарний режим: підготовка-до-вступу/історія/блоки/23-комуністичний-режим.md
              - 24. Голодомор і терор: підготовка-до-вступу/історія/блоки/24-голодомор-терор.md
              - 25. Західна Україна міжвоєнна: підготовка-до-вступу/історія/блоки/25-західна-україна-міжвоєнна.md
              - 26. Друга світова війна: підготовка-до-вступу/історія/блоки/26-друга-світова.md
              - 27. Перші повоєнні роки: підготовка-до-вступу/історія/блоки/27-перші-повоєнні-роки.md
              - 28. Десталінізація: підготовка-до-вступу/історія/блоки/28-десталінізація.md
              - 29. Криза радянської системи: підготовка-до-вступу/історія/блоки/29-криза-радянської-системи.md
              - 30. Відновлення незалежності: підготовка-до-вступу/історія/блоки/30-відновлення-незалежності.md
              - 31. Становлення незалежної України: підготовка-до-вступу/історія/блоки/31-становлення-незалежної.md
              - 32. Творення нової України: підготовка-до-вступу/історія/блоки/32-творення-нової-україни.md

      - Математика:
          - підготовка-до-вступу/математика/index.md
          - 01. Алгебра і початки аналізу: підготовка-до-вступу/математика/01-алгебра-початки-аналізу.md
          - 02. Планіметрія та стереометрія: підготовка-до-вступу/математика/02-планіметрія-стереометрія.md
          - 03. Алгебра та теорія чисел: підготовка-до-вступу/математика/03-алгебра-теорія-чисел.md
          - 04. Математичний аналіз: підготовка-до-вступу/математика/04-математичний-аналіз.md
          - 05. Геометрія (аналітична + проективна): підготовка-до-вступу/математика/05-геометрія.md
          - Типові задачі: підготовка-до-вступу/математика/типові-задачі.md

      - Українська мова:
          - підготовка-до-вступу/українська-мова/index.md
          - 01. Фонетика. Графіка. Орфоепія. Орфографія: підготовка-до-вступу/українська-мова/01-фонетика-орфоепія.md
          - 02. Лексикологія. Фразеологія: підготовка-до-вступу/українська-мова/02-лексикологія-фразеологія.md
          - 03. Будова слова. Словотвір: підготовка-до-вступу/українська-мова/03-словотвір.md
          - 04. Морфологія: підготовка-до-вступу/українська-мова/04-морфологія.md
          - 05. Синтаксис: підготовка-до-вступу/українська-мова/05-синтаксис.md
          - 06. Стилістика: підготовка-до-вступу/українська-мова/06-стилістика.md
          - 07. Розвиток мовлення: підготовка-до-вступу/українська-мова/07-розвиток-мовлення.md

      - Англійська мова:
          - підготовка-до-вступу/англійська/index.md
          - Граматика-довідник: підготовка-до-вступу/англійська/граматика-довідник.md
          - Особистісна сфера:
              - підготовка-до-вступу/англійська/особистісна-сфера/index.md
              - Повсякденне життя і його проблеми: підготовка-до-вступу/англійська/особистісна-сфера/повсякденне-життя.md
              - Сім'я. Родинні стосунки: підготовка-до-вступу/англійська/особистісна-сфера/сімя-родинні-стосунки.md
              - Характер людини: підготовка-до-вступу/англійська/особистісна-сфера/характер-людини.md
              - Режим дня: підготовка-до-вступу/англійська/особистісна-сфера/режим-дня.md
              - Здоровий спосіб життя: підготовка-до-вступу/англійська/особистісна-сфера/здоровий-спосіб-життя.md
              - Дружба, любов: підготовка-до-вступу/англійська/особистісна-сфера/дружба-любов.md
              - Стосунки з однолітками: підготовка-до-вступу/англійська/особистісна-сфера/стосунки-з-однолітками.md
              - Світ захоплень: підготовка-до-вступу/англійська/особистісна-сфера/світ-захоплень.md
              - Дозвілля, відпочинок: підготовка-до-вступу/англійська/особистісна-сфера/дозвілля-відпочинок.md
              - Особистісні пріоритети: підготовка-до-вступу/англійська/особистісна-сфера/особистісні-пріоритети.md
              - Плани на майбутнє, вибір професії: підготовка-до-вступу/англійська/особистісна-сфера/плани-на-майбутнє.md
          - Публічна сфера:
              - підготовка-до-вступу/англійська/публічна-сфера/index.md
              - Навколишнє середовище: підготовка-до-вступу/англійська/публічна-сфера/навколишнє-середовище.md
              - Життя в країні, мова якої вивчається: підготовка-до-вступу/англійська/публічна-сфера/життя-в-країні.md
              - Подорожі, екскурсії: підготовка-до-вступу/англійська/публічна-сфера/подорожі-екскурсії.md
              - Культура і мистецтво: підготовка-до-вступу/англійська/публічна-сфера/культура-мистецтво.md
              - Спорт: підготовка-до-вступу/англійська/публічна-сфера/спорт.md
              - Література: підготовка-до-вступу/англійська/публічна-сфера/література.md
              - Засоби масової інформації: підготовка-до-вступу/англійська/публічна-сфера/змі.md
              - Молодь і сучасний світ: підготовка-до-вступу/англійська/публічна-сфера/молодь-сучасний-світ.md
              - Людина і довкілля: підготовка-до-вступу/англійська/публічна-сфера/людина-довкілля.md
              - Одяг. Покупки: підготовка-до-вступу/англійська/публічна-сфера/одяг-покупки.md
              - Харчування: підготовка-до-вступу/англійська/публічна-сфера/харчування.md
              - Науково-технічний прогрес: підготовка-до-вступу/англійська/публічна-сфера/науково-технічний-прогрес.md
              - Свята, знаменні дати: підготовка-до-вступу/англійська/публічна-сфера/свята-знаменні-дати.md
              - Традиції та звичаї: підготовка-до-вступу/англійська/публічна-сфера/традиції-звичаї.md
              - Політичне життя: підготовка-до-вступу/англійська/публічна-сфера/політичне-життя.md
              - Історична та культурна спадщина: підготовка-до-вступу/англійська/публічна-сфера/історична-культурна-спадщина.md
          - Освітня сфера:
              - підготовка-до-вступу/англійська/освітня-сфера/index.md
              - Освіта, навчання, виховання: підготовка-до-вступу/англійська/освітня-сфера/освіта-навчання-виховання.md
              - Студентське життя: підготовка-до-вступу/англійська/освітня-сфера/студентське-життя.md
              - Система освіти в країні, мова якої вивчається: підготовка-до-вступу/англійська/освітня-сфера/система-освіти.md
              - Іноземні мови у житті людини: підготовка-до-вступу/англійська/освітня-сфера/іноземні-мови-у-житті.md

      - Довідники:
          - підготовка-до-вступу/довідники/index.md
          - Правила прийому 2026: підготовка-до-вступу/довідники/правила-прийому-2026.md
          - Формули розрахунку балів: підготовка-до-вступу/довідники/формули-розрахунку-балів.md
          - Корисні посилання: підготовка-до-вступу/довідники/корисні-посилання.md

  - 1 курс:
      - 1-курс/index.md
      - Семестри:
          - 1 семестр: 1-курс/1-семестр/index.md
          - 2 семестр: 1-курс/2-семестр/index.md
  - 2 курс:
      - 2-курс/index.md
      - Семестри:
          - 1 семестр: 2-курс/1-семестр/index.md
          - 2 семестр: 2-курс/2-семестр/index.md
  - 3 курс:
      - 3-курс/index.md
      - Семестри:
          - 1 семестр: 3-курс/1-семестр/index.md
          - 2 семестр: 3-курс/2-семестр/index.md
  - 4 курс:
      - 4-курс/index.md
      - Семестри:
          - 1 семестр: 4-курс/1-семестр/index.md
          - 2 семестр: 4-курс/2-семестр/index.md
  - 5 курс:
      - 5-курс/index.md
      - Семестри:
          - 1 семестр: 5-курс/1-семестр/index.md
          - 2 семестр: 5-курс/2-семестр/index.md
  - 6 курс:
      - 6-курс/index.md
      - Семестри:
          - 1 семестр: 6-курс/1-семестр/index.md
          - 2 семестр: 6-курс/2-семестр/index.md
  - 7 курс:
      - 7-курс/index.md
      - Семестри:
          - 1 семестр: 7-курс/1-семестр/index.md
          - 2 семестр: 7-курс/2-семестр/index.md
  - Аспірантура: аспірантура/index.md
  - Практика: практика/index.md

watch:
  - docs
